# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  hardware.asahi.peripheralFirmwareDirectory = /boot/asahi;
  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    options hid_apple iso_layout=0 fnmode=1 swap_opt_cmd=1
  '';
  boot.kernelParams = [
    "apple_dcp.show_notch=1" # use entire screen with notch
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/22f20df7-c092-4455-9057-697ac0c36823";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/86d205dc-bae7-44c9-8339-6f2d110212b7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E16-19FA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
